#application: hpush-quanta-777
application: hpush-dev-785
version: 1
runtime: go
api_version: go1
instance_class: F4_1G
automatic_scaling:
  max_concurrent_requests: 500

handlers:
- url: /.*
  script: _go_app
